### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#35]
It takes a long time to render the book -- why is caching turned off?

**Comment by mllg** [comment]
* If you run `./serve`, only the Rmd with changes gets recompiled after the first compilation. Unfortunately, we have very large Rmd files because bookdown requires us to put every chapter in a single file.
* We could enable a knitr cache, I don't know how well this one works though.
* Travis should run without cache.

@pat-s Have you tried to enable the cache?

**Comment by mllg** [comment]
Actually, it might be possible to split the chapters into multiple files. We should give it a shot after all open PRs are merged.

**Comment by pat-s** [comment]
> Actually, it might be possible to split the chapters into multiple files.

I tried for almost two hours around 2 weeks ago and failed.
Multiple reasons for it. 
You can try again if you have free time but I would not recommend it.

> Have you tried to enable the cache?

Yes, several times during the workshop. Simply setting `knitr::opts_chunk$set(cache = T)` does not work because you will face spurious errors that some objects were not created along the way.
I suspect that this is an R6 issue.

Currently I think that our setup with Michels `./serve` is the most convenient one we can aim for. Only the Rmd with changed made is rerun in this case.

**Comment by mllg** [comment]
Maybe we can do a video call on this. I just tried to move a subsection into a separate file, and it seemed to compile just fine.

**Comment by mllg** [comment]
For the caching: Patrick is right, this is a R6 thing. knitr saves its cache with internal functions intended for lazy loading data, and these are not working together with active bindings :(

**Comment by mllg** [comment]
Here is the issue: https://github.com/r-lib/R6/issues/152

**Comment by larskotthoff** [comment]
Ok, thanks for the clarification.

**Comment by berndbischl** [comment]
Fuck this issue and that this was closed in R6. This is a horrible language bug.
