### ISSUE TITLE
Consistent link formatting

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#409]
I talked to Bernd about link style consistency and thought I'd convert/start informal discussion into an issue for easier tracking/discussion.  
From what I understand, there are 3 types of links in the book, and they should be handled consistently:

1. Internal links to other (sub-)sections, including figures/tables.
    - Handled via [crossrefs](https://quarto.org/docs/books/book-crossrefs.html)
3. External links to other resources (websites, blog posts, ...)
    - Should be distinguishable from internal links, so `[text](url) @ref`? Would require `.bib` entries for all external links
    - Could alternatively link in a footnote?
    - Edge case: Should links to mlr-materials (pkgdown websites, gallery posts, ...) be treated differently?
5. References (papers, books, ...)
    - Regular `.bib` + `@ref` syntax

See quarto docs on [references and footnotes](https://quarto.org/docs/authoring/footnotes-and-citations.html).

Are there other types of links I forgot?  
In principle, `downlit` should handle links to R documentation for functions in code blocks, but I noticed that for example `lrn` and `tsk` aren't linked [in this section](https://mlr3book.mlr-org.com/performance.html#resampling-settings).

**Comment by pat-s** [comment]
> Should be distinguishable from internal links

What is the motiviation behind this? I don't see a direct reason to distinguish links - links are links, aren't they?

**Comment by pat-s** [comment]
No worries, every request should be discussed and thoroughly evaluated! Contributions are always encouraged!

> Additionally, treating external resources like references (with citation) feels more appropriate, but once again, that might just be my preference. Then again, I'm a "URLs in footnotes in a PDF" kind of guy, I don't expect everyone to like this approach.

I think this is quite uncommon, especially the footnotes one. Citations should clearly be citations if there is a citable resource for it, i.e. an article or a DOI. Yet linking to "normal" resources is usually then just represented by an URL/hyperlink. 

> Might be personal preference but I think there's some value in being able to distinguish "this is going to take me to a different section" and "this is going to take me to an external website", especially in the PDF version where target URLs are not (in my experience) revealed on hover.

I don't think that the difference between a bibentry and a hyperlink should be wether it's an internal or external source. Even if so, how would you distinguish them on the hyperlink level?

> Regarding motivation: I shortly talked to Bernd about the book in general and he mentioned link consistency as something to be discussed / something where he'd like some clear decision regarding what/how we do it.

Could you show some examples of links for which we are inconsistent? 

> In principle, downlit should handle links to R documentation for functions in code blocks, but I noticed that for example lrn and tsk aren't linked [in this section](https://mlr3book.mlr-org.com/performance.html#resampling-settings).

Yes, {downlit} does not fully work with R6 or even some normal functions sometimes which is why we are still using the internal `ref()` notation.

**Comment by RaphaelS1** [comment]
This is now sorted with our more consistent styling of links and the `link` function I've written
