### ISSUE TITLE
The `ref` function needs fixing

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#500]
At least it should have an argument "package" to link to external packages and should not print the `mlr3<package>::` prefix unless explicitly stated to agree with the mlr3book style guide outlined in the preface

**Comment by sebffischer** [comment]
Also if the argument `text` is provided the package prefix should always be omitted.

**Comment by RaphaelS1** [comment]
Fixing in what way? It should be able to link to external pkgs (and can currently just checked)

> should not print the mlr3<package>:: prefix unless explicitly stated to agree with the mlr3book style guide outlined in the preface

I'm keeping this for now until the end then we'll decide. Currently I disagree we should remove the prefix because it's one of the hardest parts of mlr3 (knowing which pkg a particular function belongs to).

> Also if the argument text is provided the package prefix should always be omitted.

I think there are few cases (if any) where the text argument should be used tbh. We want people to be able to find a package, they can't do that in a printed book without a link if we change the pkg name to other text

**Comment by sebffischer** [comment]
Sorry for this issue, I think I have used an old version of the mlr3book R package when rendering. Closing because of that.

**Comment by sebffischer** [comment]
Reopening because I was wrong (removed the wrong comment)

I think there are cases where having the constant `paradox::` is making the content less readable and it is clear from the context from which context the function belongs. 

I think you have a point with your second argument, but one might still provide some more convenience for the html version of the book, even though this is then not useful for the pdf version.

**Comment by RaphaelS1** [comment]
>  but one might still provide some more convenience for the html version of the book, even though this is then not useful for the pdf version.

Quarto doesn't allow switching between html/pdf options and pdf is our priority

> I think there are cases where having the constant paradox:: is making the content less readable and it is clear from the context from which context the function belongs.

In which case my strong preference would be to have an argument like `suppressPackage` which defaults to `FALSE` and if `TRUE` then suppresses the package name, thoughts?

**Comment by sebffischer** [comment]
> > but one might still provide some more convenience for the html version of the book, even though this is then not useful for the pdf version.
> 
> Quarto doesn't allow switching between html/pdf options and pdf is our priority
> 


But we could include an option like `mlr3book.output` that can be set to `"pdf"` and `"html"` and depending on the option the behaviour of the `ref()` function changes?
But maybe this is also an overkill, not sure whether we really need this. 

> > I think there are cases where having the constant paradox:: is making the content less readable and it is clear from the context from which context the function belongs.
> 
> In which case my strong preference would be to have an argument like `suppressPackage` which defaults to `FALSE` and if `TRUE` then suppresses the package name, thoughts?

Yes, but the function also always needs to suppress the prefix in case it is called like `ref("paradox::ps")`, because otherwise it is converted to `paradox::paradox::ps()`. 

And I might even argue, that the default for `suppressPackage` should be `TRUE`. 
My reasons are the following: 
1. Often (or sometimes) it is clear from the context. Sentences are like "We can call the `ps()` function from the `paradox` package. Also the section titles give information which package is currently focused on.
2. Users don't even really need to know where something is from. I think as long as something is available after calling `library(mlr3verse)`, most people don't care where the function is from. 
3. People can find out where stuff is from bye.g.  calling `environment(ps)` (maybe we should write this as a hint in the beginning of the book). 
4. I think in many cases the prefixes make it harder to read the sentences. 

A middle way would maybe be to use the prefixes in the code blocks, where I would find them less disturbing (and usually functions that are mentioned in the text are also included in the code soon afterwards). 

In those cases where it is better to also include the prefix in the text, we can then just set the `suppressPackage` argument to `FALSE`.

**Comment by RaphaelS1** [comment]
Let's go through this with examples (btw I don't disagree with you, I just think we need a comrpromise useful to users)

1. In this example clearly the prefixes are useless, we could have one sentence that says "these functions are from mlr3tuning" (I'd also argue we never need the package name for R6 Classes, only functions)

![Screenshot 2023-01-13 at 12 00 42](https://user-images.githubusercontent.com/25639974/212315703-58f9c8cf-fb51-4f0f-b7a5-7655b318ebab.png)

2. I find this an interesting case. Because `to_tune` *really* confused me, I kept looking for it in `mlr3tuning` whereas it's actually `paradox`, which seems super counterintuitive. Other examples here are `trm`, which in a way don't matter because of the dependency on bbotk (and I think it may even be an export).

![Screenshot 2023-01-13 at 12 02 01](https://user-images.githubusercontent.com/25639974/212315941-98f56466-7ff1-4fbd-a799-3e3f2eec71ae.png)

**Comment by RaphaelS1** [comment]
Looking at these examples, how about we have the following rule:

1. Objects and classes we suppress the package (as we favour sugar throughout)
2. Suppress core packages: mlr3 and paradox (I disagree everything in mlr3verse because it's a really weird selection that includes mlr3fselect and mlr3cluster...)
3. Suppress functions from packages that are being discussed in a chapter, e.g., in above example we suppress `mlr3tuning` but don't suppress `paradox` in `to_tune`. We then make case-by-case decisions for exceptions, e.g., we suppress `bbotk` because it's a paradox dependency

**Comment by RaphaelS1** [comment]
Dependency graph could be interesting but now we're in advanced territory. Similarly I think a callout box that says "our structure is confusing so use this function to work out where things are" might not be a good look!! As a compromise I'd suggest we update the preamble with a short sentence about this

**Comment by sebffischer** [comment]
ok!
