### ISSUE TITLE
Chapter 4v3 comments

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr3book#503]
Version 2 of Chapter 4 Optimization  is merged to main. Please add your comments for version 3 here.

**Comment by RaphaelS1** [comment]
Amazing thanks @be-marc ! Some final comments and then I think we should consider the chapter 'locked' for further editing until others are ready.

* [ ] The solution to exercise 3 is missing
* [ ] Can you add a small amount of text (1-2 sentences) at start of 4.2 to explain why it's 'Advanced' 
* [ ] There are broken references, please go through and check these, e.g. '?sec-fallback-learner'
* [ ] Caption for Fig 4.5 needs updating with new style
* [ ] For Fig 4.6 please can you add some text into the diagram itself that clearly says something like "The wrong way to tune"
* [ ] Can you see if you can find a way to fix the content (i.e., column sizes) in table 4.3?

**Comment by be-marc** [comment]
>  Can you see if you can find a way to fix the content (i.e., column sizes) in table 4.3?

The table with s3 and r6 classes? We cannot break `mlr3tuning::extract_inner_tuning_archives()`. But yes the summary column looks silly.

**Comment by be-marc** [comment]
![grafik](https://user-images.githubusercontent.com/33069354/212668708-a8fd7428-926e-4cd5-b1ee-fb11867d064f.png)

Since we stopped using the logscale this plot is pretty useless isn't it?

**Comment by RaphaelS1** [comment]
> The table with s3 and r6 classes? We cannot break mlr3tuning::extract_inner_tuning_archives(). But yes the summary column looks silly.

Yeah don't worry for now, I'm going to remove pkg prefixes on Fri

> Since we stopped using the logscale this plot is pretty useless isn't it?

Agreed but it is nice to show and explain that plot. Anywhere else we could have a version of the plot?

**Comment by be-marc** [comment]
> Agreed but it is nice to show and explain that plot. Anywhere else we could have a version of the plot?

Maybe we should add logscale to the search space again?

**Comment by RaphaelS1** [comment]
> Maybe we should add logscale to the search space again? Logscale is now in the last section. Before the plot is useless.

Could we move the plot later on and reference it earlier?

**Comment by larskotthoff** [comment]
At the very beginning of the chapter, the seed is set without any explanation. Briefly explain why the seed should be set and how reproducibility is affected (especially important for tuning).

I think that mentioning multi-fidelity and multi-objective HPO (without much detail) at the beginning of the chapter is a bit overwhelming. In particular multi-fidelity tuning isn't even mentioned again afterwards. I would move this and expand into a (short) section, or remove.

I would briefly mention random search and grid search in the introduction, as methods that the reader is probably already familiar with.

When discussing search spaces, I would briefly mention that the limits given in a param_set are what's technically possible, but in practice the ranges should be narrowed.

In 4.1.2, mention for the combo terminator how conditions are combined (and? or?). Where do the names (`run_time_100`) come from?

At the end of 4.1.6, briefly explain why the classification error isn't the same with the same HP settings.

I think the warning at the end of 4.1.8 that you should really use a nested resampling is a bit hidden, given its importance. It would be great to have an example to illustrate this, e.g. simply train the optimized model on part of sonar and evaluate on the rest, showing that the performance is not as good as expected.

In 4.2.1, explain what the "evaluate" means when encapsulating learners, and what the other options are. The example just below isn't particularly great because there are no errors or warnings.

In 4.2.2 I'm not sure if the histograms at the beginning help (seems pretty obvious), but the section doesn't say *why* we want to sample on a log scale. At the end of the section, say how these transformed values are used -- if I set the optimized HPs as in section 4.1.8, will the learner get the "log" values that I need to transform, or the actual values I want to set? The text seems to imply that I can't directly set the HPs but have to transform them manually or get them from x_domain.

In 4.2.3, the reference to `TuneTokens` is confusing. It links to a man page that doesn't mention tokens or the `lts()` function that is used in the code below at all.

4.3 uses a different dataset/learner. Could this be the same "running example"? The code to generate the Pareto front plot is not given but would be useful.

Figure 4.6 isn't clear. What does the different color for the arrows mean? Why do I get the optimal configuration from a single pass? Shouldn't there be a performance estimate for the optimal configuration as well? I think the concept would be better illustrated with the usual Gedankenexperiment of having HPs that don't do anything rather than a figure.

4.5 says that nested resampling is not a procedure for choosing optimal HPs, which begs the obvious question of what is. The whole section kind of leaves you hanging -- what we've done before actually only gives us biased performance estimates (so probably shouldn't do that?) but nested resamplings shouldn't be used to choose optimal HPs either. Explicitly say how to do this in practice (can use analogy to ML here, i.e. model trained on the entire data and its performance estimated through e.g. a CV).

Should Q2 in the exercises say "evaluate the performance of the models *induced by the hyperparameters*..."? Seems that something about HPs is missing there.

**Comment by RaphaelS1** [comment]
@be-marc  is it possible to change `spam` -> `sonar`?

**Comment by be-marc** [comment]
## Notes for the next meeting

> At the very beginning of the chapter, the seed is set without any explanation. Briefly explain why the seed should be set and how reproducibility is affected (especially important for tuning).

We need a new agreement there. Previously, a new seed was set in each chapter. If we don't do that anymore, we can explain the seed in the optimization chapter.

> I think that mentioning multi-fidelity and multi-objective HPO (without much detail) at the beginning of the chapter is a bit overwhelming. In particular multi-fidelity tuning isn't even mentioned again afterwards. I would move this and expand into a (short) section, or remove.

@sumny 

> I would briefly mention random search and grid search in the introduction, as methods that the reader is probably already familiar with.

Yes and @sumny 

> When discussing search spaces, I would briefly mention that the limits given in a param_set are what's technically possible, but in practice the ranges should be narrowed.

Yes

> In 4.1.2, mention for the combo terminator how conditions are combined (and? or?). Where do the names (run_time_100) come from?

I think `run_time_100` is very understandable. We can explain `any` and `all` from `"combo"`.

> At the end of 4.1.6, briefly explain why the classification error isn't the same with the same HP settings.

I am not sure about that. This could confuse the reader if he notices it. The results of the two runs are shown very close together. If he doesn't notice it, the info could be too distracting.

> I think the warning at the end of 4.1.8 that you should really use a nested resampling is a bit hidden, given its importance. It would be great to have an example to illustrate this, e.g. simply train the optimized model on part of sonar and evaluate on the rest, showing that the performance is not as good as expected.

I would not start splitting the data set beforehand. This is just an extra step that the user does not need when tuning.

> In 4.2.1, explain what the "evaluate" means when encapsulating learners, and what the other options are. The example just below isn't particularly great because there are no errors or warnings.

We could use `LearnerClassifDebug` to force errors.

> In 4.2.2 I'm not sure if the histograms at the beginning help (seems pretty obvious), but the section doesn't say why we want to sample on a log scale. At the end of the section, say how these transformed values are used -- if I set the optimized HPs as in section 4.1.8, will the learner get the "log" values that I need to transform, or the actual values I want to set? The text seems to imply that I can't directly set the HPs but have to transform them manually or get them from x_domain.

Yes. We should consider this when merging with @sebffischer part. We should add that  `to_tune` takes the bounds on the learner scale.

> 4.3 uses a different dataset/learner. Could this be the same "running example"? The code to generate the Pareto front plot is not given but would be useful.

`spam` to `sonar`?

> Figure 4.6 isn't clear. What does the different color for the arrows mean? Why do I get the optimal configuration from a single pass? Shouldn't there be a performance estimate for the optimal configuration as well? I think the concept would be better illustrated with the usual Gedankenexperiment of having HPs that don't do anything rather than a figure.

I don't find them that understandable either. Gedankenexperiment might be good.

> 4.5 says that nested resampling is not a procedure for choosing optimal HPs, which begs the obvious question of what is. The whole section kind of leaves you hanging -- what we've done before actually only gives us biased performance estimates (so probably shouldn't do that?) but nested resamplings shouldn't be used to choose optimal HPs either. Explicitly say how to do this in practice (can use analogy to ML here, i.e. model trained on the entire data and its performance estimated through e.g. a CV).

@RaphaelS1 Didn't you rewrite that section to address this?

> Should Q2 in the exercises say "evaluate the performance of the models induced by the hyperparameters..."? Seems that something about HPs is missing there.

Yes
