### ISSUE TITLE
Package links are rendered incorrectly in the html version

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#746]
E.g. in the first chapter, some links are rendered as `r mlr3pipelines`

**Comment by RaphaelS1** [comment]
definitely html only not pdf? also that's very strange because we would've noticed when proofreading, is this a new bug?

**Comment by jemus42** [comment]
It looks fine in the PDF version, at least the one linked on the book website currently:

![image](https://github.com/mlr-org/mlr3book/assets/1613346/81c5a8bd-3797-4e7b-ac9c-5b68f6f3a812)

But I don't quite understand how that's possible unless the PDF is generated differently than the HTML in terms of which code is executed where and what's available when.

The issue is probably that the first page is generated from `index.qmd` which doesn't include `common/_setup.qmd` like other chapters, and that's where the `mlr3book` package is loaded, and that's where the package-name-as-links are defined.

I tried adding 

```
{{< include common/_setup.qmd >}}
```

to `index.qmd` but the problem is the relative paths - `setup.qmd` in turn contains an include

```
{{< include ../../common/_utils.qmd >}}
```
...but that relative path breaks in this context because `index.qmd` is in a different hierarchy level than all the other chapters.


Anyway the simple solution was to just load `mlr3book` in a chunk at the top of `index.qmd`, see #755
